### ISSUE TITLE
A request..

### ISSUE THREAD

**Issue by weida2** [delilah-csp/delilah#2]
Hello, I am a master student in the Storage Laboratory of Huazhong University of Science and Technology. I have read your paper on Delilah, is there a more detailed introduction document on Delilah

**Comment by niclashedam** [comment]
Hi Wei! Sorry for the two-week latency. Denmark was in the middle of summer vacation, so the gears ran slowly.

First, thanks for taking the time to read my paper! Delilah is still very new, so we have not published any other publications. However, if you have questions about Delilah or related work, I am happy to answer them.

**Comment by niclashedam** [comment]
It has been two weeks since I updated this issue, and I have yet to hear from you. I will close this issue. Please feel free to reopen it if you have any more questions.
